# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 879dcd8f303da25f418854b349f03ef787ac6a0ce33fa252f4f07c1263816eebd5b1296025486fa4a850bfd435fb16b95ace643271d09f2c3d8151fcd36c191c

test:
  secret_key_base: 91201d59ad583f8b26df43daddacbea70cb8fabf2cc9c0a1d10a5502350b1e9d36cba52c37cb9ce115151ae914a9ea86757d37c5968aab862fb998e7705df1a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
